[[main]]
  identifier = "Post"
  name = "Post"
  title = "发布"
  url = "/post/"
  weight = 10
[[main]]
  identifier = "Index"
  name = "Index"
  title = "索引"
  weight = 20
[[main]]
  parent = "Index"
  name = "Categories"
  title = "类目"
  url = "/categories/"
  weight = 21
[[main]]
  parent = "Index"
  name = "Tags"
  title = "标签"
  url = "/tags/"
  weight = 22
[[main]]
  identifier = "About"
  name = "About"
  title = "关于"
  weight = 30
[[main]]
  parent = "About"
  name = "Author"
  title = "作者"
  url = "/authors"
  weight = 31
[[main]]
  parent = "About"
  name = "GitHub"
  title = "GitHub"
  url = "https://github.com/YXL76"
  weight = 32
[[main]]
  parent = "About"
  name = "Log"
  title = "日志"
  url = "/log"
  weight = 33