countryCode = "CN"
description = "～已经没什么好害怕的了!～"
postCopyright = "原文地址：[{{ .Permalink }}]({{ .Permalink }})\n\n转载时必须以链接形式注明原始出处。"

[search]
  #   0: Nothing
  #   1: Algolia (https://www.algolia.com)
  #   2: Google (https://cse.google.com/)
  engine = 2

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = "OIIAO42ZPQ"
    api_key = "c5a73fdddfb9ce2f1c82e3b17c9e68cb"
    index_name = "Blog"
    # page variables
    vars = ["Title", "Summary", "Date", "Lastmod", "Permalink", "WordCount"]
    # custom page variables
    params = ["categories", "tags"]

  [search.google]
    key = "AIzaSyDtJ9nsqTmuLGcvgAmavJ5X7n1drzIeYXc"
    cx = "012393991450560571101:gynxbarmlec"