countryCode = "US"
description = "~ There is nothing to be afraid of! ~"
postCopyright = "Original link：[{{ .Permalink }}]({{ .Permalink }})\n\nWhen reprinting, the original source must be indicated in the form of a link."

[search]
  #   0: Disabled
  #   1: Algolia (https://www.algolia.com)
  #   2: Google (https://cse.google.com/)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = "OIIAO42ZPQ"
    api_key = "c5a73fdddfb9ce2f1c82e3b17c9e68cb"
    index_name = "en"
    # page variables
    vars = ["Title", "Summary", "Permalink"]
    # custom page variables
    params = ["categories", "tags"]

  [search.google]
    key = "AIzaSyDtJ9nsqTmuLGcvgAmavJ5X7n1drzIeYXc"
    cx = "012393991450560571101:gynxbarmlec"