name: Build

on:
  push:
    paths-ignore:
      - "src/**"
      - "static/**"
      - "assets/**"
      - "config/**"
      - "content/**"
      - "gatsby-**.ts"
      - "gatsby-config.js"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Get yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Get gatsby cache
        uses: actions/cache@v2
        with:
          path: |
            .cache
            public
          key: gatsby-${{ hashFiles('**/gatsby-node.ts') }}-${{ hashFiles('**/gatsby-config.ts') }}-${{ hashFiles('**/gatsby-browser.ts') }}
          restore-keys: |
            gatsby-${{ hashFiles('**/gatsby-node.ts') }}-${{ hashFiles('**/gatsby-config.ts') }}-

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GITALK_CLIENT_ID: ${{ secrets.GITALK_CLIENT_ID }}
          GITALK_CLIENT_SECRET: ${{ secrets.GITALK_CLIENT_SECRET }}
